/*
 * generated by Xtext 2.20.0
 */
package sdu.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IoTStandaloneSetup extends IoTStandaloneSetupGenerated {

	def static void doSetup() {
		new IoTStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
