/*
 * generated by Xtext 2.20.0
 */
package sdu.mdsd.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import sdu.mdsd.ioT.Model

@ExtendWith(InjectionExtension)
@InjectWith(IoTInjectorProvider)
class IoTParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			iot test {
				var x = 5
			}
		''')
		Assert.assertEquals(result.devices.get(0).name, 'test')
		Assert.assertEquals(result.devices.get(0).program.variables.get(0).name, 'x')
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	

}
